"""make Event.created nullable

Revision ID: d6ad912197d5
Revises: 6ab712d9e3da
Create Date: 2020-11-29 18:17:40.636585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d6ad912197d5"
down_revision = "6ab712d9e3da"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.alter_column("created", existing_type=sa.DATETIME(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.alter_column("created", existing_type=sa.DATETIME(), nullable=False)

    # ### end Alembic commands ###
