"""add last learned field

Revision ID: a966d3779635
Revises: 7844a7ef9ea4
Create Date: 2020-11-22 22:09:14.421372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a966d3779635"
down_revision = "7844a7ef9ea4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_learned", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_column("last_learned")

    # ### end Alembic commands ###
