"""remove Item.repitition_number and last_learned

Revision ID: 6ab712d9e3da
Revises: e0ee2d1717b3
Create Date: 2020-11-29 18:15:22.533569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6ab712d9e3da"
down_revision = "e0ee2d1717b3"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("PRAGMA FOREIGN_KEYS=off")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_column("last_learned")
        batch_op.drop_column("repitition_number")
    op.execute("PRAGMA FOREIGN_KEYS=on")
    # ### end Alembic commands ###


def downgrade():
    op.execute("PRAGMA FOREIGN_KEYS=off")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("repitition_number", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("last_learned", sa.DATETIME(), nullable=True))
    op.execute("PRAGMA FOREIGN_KEYS=on")
    # ### end Alembic commands ###
