"""add next_iteration field

Revision ID: e9f39cd18f6f
Revises: a966d3779635
Create Date: 2020-11-22 23:40:30.533488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e9f39cd18f6f"
down_revision = "a966d3779635"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("next_iteration", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_column("next_iteration")

    # ### end Alembic commands ###
