"""Add is_active flag

Revision ID: 40f1811f3199
Revises: d6ad912197d5
Create Date: 2021-04-10 12:35:14.604068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "40f1811f3199"
down_revision = "d6ad912197d5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.alter_column("item_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_active", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_column("is_active")

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.alter_column("item_id", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###
