"""add token field to User

Revision ID: 09b934cf2774
Revises: 40f1811f3199
Create Date: 2021-04-13 02:07:48.493706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "09b934cf2774"
down_revision = "40f1811f3199"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("token", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column("token_expires", sa.DateTime(), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_users_token"), ["token"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_token"))
        batch_op.drop_column("token_expires")
        batch_op.drop_column("token")

    # ### end Alembic commands ###
