"""update fk constraints

Revision ID: c5794a5bf635
Revises: 5b64162fd45f
Create Date: 2023-02-05 11:45:45.552602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c5794a5bf635"
down_revision = "5b64162fd45f"
branch_labels = None
depends_on = None


naming_convention = {
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "events", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.drop_constraint("fk_events_item_id_items", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_events_item_id_items"),
            "items",
            ["item_id"],
            ["id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        )

    with op.batch_alter_table(
        "items", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f("uq_items_user_id"), ["user_id", "word"]
        )
        batch_op.drop_constraint("fk_items_user_id_users", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_items_user_id_users"),
            "users",
            ["user_id"],
            ["id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        )

    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f("uq_settings_user_id"), ["user_id"]
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f("uq_users_username"), ["username"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_users_username"), type_="unique")

    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_settings_user_id"), type_="unique")

    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_items_user_id_users"), type_="foreignkey"
        )
        batch_op.create_foreign_key(None, "users", ["user_id"], ["id"])
        batch_op.drop_constraint(batch_op.f("uq_items_user_id"), type_="unique")

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_events_item_id_items"), type_="foreignkey"
        )
        batch_op.create_foreign_key(None, "items", ["item_id"], ["id"])

    # ### end Alembic commands ###
