"""add max_trainings to settings table

Revision ID: 8507e230a469
Revises: c5794a5bf635
Create Date: 2023-02-05 11:53:12.773434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8507e230a469"
down_revision = "c5794a5bf635"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("max_trainings", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.drop_column("max_trainings")

    # ### end Alembic commands ###
