import random

filenames = [
    "animals/svg/001-elephant.svg",
    "animals/svg/002-hen.svg",
    "animals/svg/003-seal.svg",
    "animals/svg/004-frog.svg",
    "animals/svg/005-dolphin.svg",
    "animals/svg/006-parrot.svg",
    "animals/svg/007-whale.svg",
    "animals/svg/008-snake.svg",
    "animals/svg/009-walrus.svg",
    "animals/svg/010-squid.svg",
    "animals/svg/011-flamingo.svg",
    "animals/svg/012-squirrel.svg",
    "animals/svg/013-crab.svg",
    "animals/svg/014-toucan.svg",
    "animals/svg/015-monkey.svg",
    "animals/svg/016-fish.svg",
    "animals/svg/017-snail.svg",
    "animals/svg/018-horse.svg",
    "animals/svg/019-jellyfish.svg",
    "animals/svg/020-rabbit.svg",
    "animals/svg/021-seahorse.svg",
    "animals/svg/022-pig.svg",
    "animals/svg/023-octopus.svg",
    "animals/svg/024-kiwi.svg",
    "animals/svg/025-duck.svg",
    "animals/svg/026-swan.svg",
    "animals/svg/027-deer.svg",
    "animals/svg/028-hermit crab.svg",
    "animals/svg/029-kangaroo.svg",
    "animals/svg/030-lobster.svg",
    "animals/svg/031-turtle.svg",
    "animals/svg/032-lion.svg",
    "animals/svg/033-cat.svg",
    "animals/svg/034-panda bear.svg",
    "animals/svg/035-owl.svg",
    "animals/svg/036-koala.svg",
    "animals/svg/037-dog.svg",
    "animals/svg/038-sheep.svg",
    "animals/svg/039-giraffe.svg",
    "animals/svg/040-meerkat.svg",
    "animals/svg/041-llama.svg",
    "animals/svg/042-shark.svg",
    "animals/svg/043-bison.svg",
    "animals/svg/044-hippopotamus.svg",
    "animals/svg/045-penguin.svg",
    "animals/svg/046-chameleon.svg",
    "animals/svg/047-camel.svg",
    "animals/svg/048-ostrich.svg",
    "animals/svg/049-bee.svg",
    "animals/svg/050-hedgehog.svg",
    "marine/svg/001-building.svg",
    "marine/svg/002-ship.svg",
    # "marine/svg/003-gauge.svg",
    "marine/svg/004-yacht.svg",
    "marine/svg/005-window.svg",
    "marine/svg/006-boat.svg",
    "marine/svg/007-boat.svg",
    "marine/svg/008-wheel.svg",
    "marine/svg/009-viking.svg",
    # "marine/svg/010-view.svg",
    "marine/svg/011-vehicle.svg",
    # "marine/svg/012-book.svg",
    "marine/svg/013-boat.svg",
    # "marine/svg/014-weapon.svg",
    "marine/svg/015-hovercraft.svg",
    # "marine/svg/016-radio.svg",
    "marine/svg/017-vehicle.svg",
    "marine/svg/018-plane.svg",
    "marine/svg/019-buoy.svg",
    "marine/svg/020-boat.svg",
    # "marine/svg/021-target.svg",
    "marine/svg/022-insurance.svg",
    "marine/svg/023-ship.svg",
    "marine/svg/024-teaching.svg",
    # "marine/svg/025-license.svg",
    "marine/svg/026-boat.svg",
    # "marine/svg/027-keys.svg",
    "marine/svg/028-pirates.svg",
    # "marine/svg/029-location.svg",
    "marine/svg/030-steam.svg",
    # "marine/svg/031-oars.svg",
    "marine/svg/032-boat.svg",
    # "marine/svg/033-navy.svg",
    "marine/svg/034-directions.svg",
    # "marine/svg/035-mine.svg",
    # "marine/svg/036-rope.svg",
    # "marine/svg/037-jacket.svg",
    # "marine/svg/038-knot.svg",
    "marine/svg/039-dinghy.svg",
    # "marine/svg/040-knot.svg",
    "marine/svg/041-message.svg",
    # "marine/svg/042-knot.svg",
    "marine/svg/043-blades.svg",
    "marine/svg/044-sail.svg",
    # "marine/svg/045-weapon.svg",
    "marine/svg/046-helicopter.svg",
    "marine/svg/047-ship.svg",
    # "marine/svg/048-whistle.svg",
    "marine/svg/049-guard.svg",
    "marine/svg/050-hat.svg",
    # "marine/svg/051-knot.svg",
    # "marine/svg/052-engine.svg",
    # "marine/svg/053-knot.svg",
    "marine/svg/054-anchor.svg",
    # "marine/svg/055-knot.svg",
    "marine/svg/056-sailor.svg",
    "marine/svg/057-anchor.svg",
    "marine/svg/058-sailor.svg",
    "marine/svg/059-wind.svg",
    "marine/svg/060-pirate.svg",
    "marine/svg/061-submarine.svg",
    # "marine/svg/062-medal.svg",
    # "marine/svg/063-oil.svg",
    "marine/svg/064-boat.svg",
    # "marine/svg/065-lifeboat.svg",
    "marine/svg/066-venice.svg",
    # "marine/svg/067-lifeboat.svg",
    # "marine/svg/068-sign.svg",
    "marine/svg/069-shark.svg",
    # "marine/svg/070-sign.svg",
    # "marine/svg/071-life guard.svg",
    # "marine/svg/072-sign.svg",
    "marine/svg/073-lifeboat.svg",
    # "marine/svg/074-harbour.svg",
    # "marine/svg/075-sign.svg",
    # "marine/svg/076-crane.svg",
    # "marine/svg/077-flare.svg",
    "marine/svg/078-ship.svg",
    # "marine/svg/079-boat.svg",
    # "marine/svg/080-amphibious car.svg",
    "sailor/svg/001-ship.svg",
    # "sailor/svg/002-barrel.svg",
    "sailor/svg/003-fish.svg",
    # "sailor/svg/004-fish hook.svg",
    "sailor/svg/005-submarine.svg",
    "sailor/svg/006-sun.svg",
    "sailor/svg/007-dolphin.svg",
    # "sailor/svg/008-spyglass.svg",
    "sailor/svg/009-snorkel.svg",
    # "sailor/svg/010-helm.svg",
    "sailor/svg/011-life jacket.svg",
    "sailor/svg/012-motorboat.svg",
    "sailor/svg/013-boat engine.svg",
    # "sailor/svg/014-Paddles.svg",
    "sailor/svg/015-map.svg",
    "sailor/svg/016-sailor.svg",
    "sailor/svg/017-shirt.svg",
    "sailor/svg/018-message in a bottle.svg",
    # "sailor/svg/019-pipe.svg",
    "sailor/svg/020-starfish.svg",
    # "sailor/svg/021-oxygen.svg",
    "sailor/svg/022-windrose.svg",
    "sailor/svg/023-shark.svg",
    "sailor/svg/024-lighthouse.svg",
    "sailor/svg/025-radar.svg",
    "sailor/svg/026-binocular.svg",
    "sailor/svg/027-sailboat.svg",
    "sailor/svg/028-captain.svg",
    # "sailor/svg/029-hat.svg",
    "sailor/svg/030-seagull.svg",
    "sailor/svg/031-whale.svg",
    "sailor/svg/032-anchor.svg",
    "sailor/svg/033-compass.svg",
    "sailor/svg/034-buoy.svg",
    "sailor/svg/035-lifesaver.svg",
    "sailor/svg/036-fishing rod.svg",
    "sailor/svg/037-storm.svg",
    "sailor/svg/038-captain.svg",
    "sailor/svg/039-boat porthole.svg",
    "sailor/svg/040-diving helmet.svg",
    "sailor/svg/041-flag pole.svg",
    "sailor/svg/042-fins.svg",
    "sailor/svg/043-cleaning.svg",
    "sailor/svg/044-shell.svg",
    "sailor/svg/045-worm.svg",
    "sailor/svg/046-crab.svg",
    # "sailor/svg/047-box.svg",
    # "sailor/svg/048-bell tower.svg",
    "sailor/svg/049-sailor.svg",
    # "sailor/svg/050-saber.svg",
]

W = dict(
    sailor=10,
    marine=10,
    animals=1,
)

weights = [W[x.split("/", 1)[0]] for x in filenames]


def get_random_image():
    filename = random.choices(filenames, weights=weights, k=1)[0]
    path = "vendor/" + filename
    return path
